# Generated by Django 4.2.10 on 2024-09-03 07:18

from django import migrations
from django.contrib.contenttypes.models import ContentType


def transfer_individual_to_recipient(apps, schema_editor):
    BenefitConsumption = apps.get_model('payroll', 'BenefitConsumption')
    Individual = apps.get_model('individual', 'Individual')  # Adjust if Individual is in a different app
    
    individual_content_type = ContentType.objects.get_for_model(Individual)
    BenefitConsumption.objects.update(
        recipient_id=django.db.models.F('individual_id'),
        recipient_type=ContentType.objects.get_for_model(Individual)
        )

class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payroll", "0021_auto_20240715_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitconsumption',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='benefitconsumption',
            name='recipient_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.DO_NOTHING,
                to='contenttypes.contenttype',
                default=ContentType.objects.get_for_model(Individual).id,
                related_name='benefit_consumption_recipient_type',
            ),
        ),
        migrations.AddField(
            model_name="historicalbenefitconsumption",
            name="recipient_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalbenefitconsumption",
            name="recipient_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                default=ContentType.objects.get_for_model(Individual).id,
            ),
        ),
        migrations.RunPython(transfer_individual_to_recipient),
    ]
