# Generated by Django 4.2.28 on 2026-02-22 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0022_alter_csvreconciliationupload_user_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpayroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("GENERATING", "GENERATING"),
                    ("PENDING_APPROVAL", "PENDING_APPROVAL"),
                    ("APPROVE_FOR_PAYMENT", "APPROVE_FOR_PAYMENT"),
                    ("REJECTED", "REJECTED"),
                    ("RECONCILED", "RECONCILED"),
                    ("FAILED", "FAILED"),
                ],
                default="GENERATING",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("GENERATING", "GENERATING"),
                    ("PENDING_APPROVAL", "PENDING_APPROVAL"),
                    ("APPROVE_FOR_PAYMENT", "APPROVE_FOR_PAYMENT"),
                    ("REJECTED", "REJECTED"),
                    ("RECONCILED", "RECONCILED"),
                    ("FAILED", "FAILED"),
                ],
                default="GENERATING",
                max_length=100,
            ),
        ),
    ]
