# Generated by Django 4.2.10 on 2024-09-03 07:22
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ("payroll", "0022_remove_benefitconsumption_individual_and_more"),
    ]

    

    operations = [
        migrations.RemoveField(
            model_name="benefitconsumption",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="historicalbenefitconsumption",
            name="individual",
        ),
        migrations.AddField(
            model_name="benefitconsumption",
            name="benefit_plan_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="benefitconsumption",
            name="benefit_plan_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.DO_NOTHING,
                related_name="benefit_consumption_benefit_plan_type",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="historicalbenefitconsumption",
            name="benefit_plan_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalbenefitconsumption",
            name="benefit_plan_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="csvreconciliationupload",
            name="user_created",
            field=models.ForeignKey(
                db_column="UserCreatedUUID",
                on_delete=django.db.models.DO_NOTHING,
                related_name="%(class)s_user_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="csvreconciliationupload",
            name="user_updated",
            field=models.ForeignKey(
                db_column="UserUpdatedUUID",
                on_delete=django.db.models.DO_NOTHING,
                related_name="%(class)s_user_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
