# Generated by Django 4.2.28 on 2026-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0024_benefit_bill_code_sequences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefitconsumption",
            name="code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalbenefitconsumption",
            name="code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
